name: S3 Ninja and OSSPerf Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '11 18 * * *'
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Remove Existing S3ninja Container
      run: |
        if [ $(docker ps -aq -f name=s3ninja) ]; then
         docker stop s3ninja
         docker rm s3ninja
        fi     
        sleep 5

    - name: Start S3 Ninja Server
      run: |
        docker pull scireum/s3-ninja
        docker run -d --name s3ninja -p  9444:9000 scireum/s3-ninja:6.1
        docker logs s3ninja     

    - name: Wait for S3 Ninja Server to Start
      run: |
        sleep 5

#    - name: Configure AWS CLI
#      env:
#        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
#        AWS_DEFAULT_REGION: eu-central-1 
#        AWS_URL: localhost:9444/s3/  
#      run: |
#        aws configure set default.region eu-central-1
#        aws configure set default.s3.endpoint_url localhost:9444/s3/
#        # aws configure set aws_access_key_id TEST_ACCESS_KEY
#         aws configure set aws_secret_access_key TEST_SECRET_KEY
        
        

    - name: Run ossperf.sh
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ossperf.sh
        ./ossperf.sh -n 10 -s 5000 -u -p -o 2>&1
#        ./ossperf.sh -n 10 -s 5000 -u -p 
